language: shell

os:
  - linux
  - osx
  - freebsd

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - jq
  homebrew:
    packages:
      - jq

before_install:
  - if [ $TRAVIS_OS_NAME = "freebsd" ]; then sudo pkg install jq; fi

install:
  - curl https://ziglang.org/download/index.json | jq -r '.master."x86_64-linux".tarball' | wget -i - -O tarball.tar.xz
  - tar xf tarball.tar.xz
  - mv zig-linux-x86_64-*/ bin

script:
  - ./bin/zig build test
